### ISSUE TITLE
Loadings: need to transform?

### ISSUE THREAD

**Issue by DominiqueMakowski** [erichson/spca#6]
Another naive question (I'm totally new to sparse PCA)

Based on my understanding, loadings would be obtained from base R like this:

``` r
x <- stats::prcomp(mtcars[1:7], scale.=TRUE)
as.data.frame(x$rotation %*% diag(x$sdev))
#>              V1          V2          V3           V4          V5          V6
#> mpg  -0.9308661  0.08921934 -0.14190532 -0.304732440  0.07657473  0.02479411
#> cyl   0.9578708  0.08435906 -0.11041606 -0.077068186 -0.08578263 -0.21498093
#> disp  0.9528463 -0.08861521  0.06931546 -0.233548878 -0.05357238  0.04453532
#> hp    0.8744936  0.36238351  0.11905715  0.002736035  0.29920238 -0.01269125
#> drat -0.7468681  0.48242879  0.44353782 -0.046525920 -0.07979742 -0.06422640
#> wt    0.8825092 -0.34667931  0.25871071 -0.042660586 -0.05996849  0.10083788
#> qsec -0.5410937 -0.80584767  0.17287686 -0.024394006  0.11796523 -0.11219509
#>                V7
#> mpg   0.077787361
#> cyl   0.060501313
#> disp -0.141521219
#> hp    0.008592570
#> drat -0.008213103
#> wt    0.135924233
#> qsec -0.029019935
```

<sup>Created on 2022-09-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Is it the same procedure for sparse PCA, or is the loadings object already "transformed"? I am asking because they look somewhat close to the rotation object from prcomp

``` r
x <- sparsepca::spca(mtcars[1:7], scale=TRUE, verbose=FALSE)
x$loadings
#>            [,1]        [,2]       [,3]        [,4]       [,5]         [,6]
#> [1,] -0.4067034  0.03034111 -0.1945205 -0.78880365  0.1625421  0.003051275
#> [2,]  0.4426563  0.06957034 -0.1266267 -0.11582098 -0.1706021 -0.806862969
#> [3,]  0.4265576 -0.05991367  0.1386627 -0.57927812 -0.1484543  0.111840195
#> [4,]  0.3285638  0.29844989  0.1197293  0.00000000  0.8790394  0.000000000
#> [5,] -0.2995167  0.42409816  0.8083783 -0.06349881 -0.1401222 -0.207842015
#> [6,]  0.4584374 -0.29855240  0.4023873 -0.08607073 -0.1222445  0.377545928
#> [7,] -0.2174315 -0.79395709  0.2958025  0.00000000  0.3030933 -0.335921867
#>            [,7]
#> [1,]  0.3526746
#> [2,]  0.2451427
#> [3,] -0.6277960
#> [4,]  0.0000000
#> [5,]  0.0000000
#> [6,]  0.5860127
#> [7,] -0.1302606
```

<sup>Created on 2022-09-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by erichson** [comment]
This is a loaded question, because different sources define loadings differently! :) Within the SPCA package the loadings denote the sparse eigenvectors (i.e., a matrix whose columns contain the sparse eigenvectors), which are not scaled (!). This is in analogy to princomp where the loadings return the unscaled eigenvectors. From looking to the documentation of prcomp it seems that prcomp is using the value rotation to denote the unscaled eigenvectors.

In your example above, you scale the the eigenvectors (which is often also called whitening). In my paper for the rsvd package on p.25 I define this also as the loadings (https://arxiv.org/pdf/1608.02148.pdf). 

Anyways, I am not consistent here with the standard terminology. But consistent with princomp and a few other SPCA packages (I guess). Long story short, SPCA does not provide the scaled loadings (I never thought about this in the context of sparse PCA). 
 
Terminology for PCA/ SPCA is a bit confusing.

**Comment by DominiqueMakowski** [comment]
So in other words it's "okay" to apply this scaling to the loadings returned by spca?

**Comment by erichson** [comment]
Yes you can scale the sparse eigenvectors if you like (again, I am not sure if that is meaningful, since I never thought about it). Btw. I recall that I adopted the the namings from the spca package (https://rdrr.io/cran/elasticnet/man/spca.html) by Hui Zou and Trevor Hastie, so that my package can be used as drop-in replacement for spca.

**Comment by DominiqueMakowski** [comment]
awesome, thanks for the info!
